name: run_tests

on:
  push:
    paths:
      - .github/workflows/run_tests.yml
      - investpy/**
      - tests/**

jobs:
  run-investpy-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip and install requirements
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[tests]
    
    - name: Run pytest tests and check codecov
      run: pytest --cov-report term --cov=investpy tests/
